# Generated by Django 3.1.6 on 2021-02-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Canned', 'Canned_foods'), ('Vegies', 'Vegetables'), ('Spice', 'Spices'), ('Bakery', 'Bakery')], max_length=60),
        ),
    ]
