# Generated by Django 3.1.6 on 2021-02-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_auto_20210204_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='labels',
        ),
    ]
