# Generated by Django 3.1.6 on 2021-02-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_auto_20210204_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='OrderItem',
        ),
    ]
